export const CATALOG = {
  GENERAL: {
    MESSAGES: {
      INTERNAL_SERVER_ERROR: "Internal Server Error",
    },
  },
  USERS: {
    MESSAGES: {
      EMAIL_ALREADY_EXISTS: "Email already exists",
      USERNAME_ALREADY_EXISTS: "Username already exists",
      INVALID_FORMAT: "Invalid format",
      NOT_FOUND: "User not found",
      MISSING_ID: "Missing User id",
      REGISTER_ERROR: "Error registering user",
      REGISTER_SUCCESS: "User registered",
      GET_BY_ID_ERROR: "Error getting user",
      GET_BY_ID_SUCCESS: "User retrieved with id: ",
      GET_BY_EMAIL_ERROR: "Error getting user by email",
      GET_BY_EMAIL_SUCCESS: "User retrieved with email: ",
      GET_BY_USERNAME_ERROR: "Error getting user by username",
      GET_BY_USERNAME_SUCCESS: "User retrieved with username: ",
      LOGIN_USERNAME_ERROR: "Error logging in user by username",
      LOGIN_USERNAME_SUCCESS: "User logged in with username",
      LOGIN_EMAIL_ERROR: "Error logging in user by email",
      LOGIN_EMAIL_SUCCESS: "User logged in with email",
      LOGOUT_ERROR: "Error logging out user",
      LOGOUT_SUCCESS: "User logged out",
    },
  },
  BRANDS: {
    MESSAGES: {
      GET_ALL_SUCCESS: "All Brands retrieved",
      GET_ALL_ERROR: "Error getting brands",
      GET_ALL_WITH_PAGINATION_ERROR: "Error getting brands with pagination",
      GET_ALL_WITH_PAGINATION_SUCCESS: "All Brands retrieved with pagination",
      GET_ALL_WITH_FILTER_ERROR: "Error getting brands with filter",
      GET_ALL_WITH_FILTER_SUCCESS: "All Brands retrieved with filter",
      GET_BY_ID_ERROR: "Error getting brand",
      GET_BY_ID_SUCCESS: "Brand retrieved with id: ",
      CREATE_SUCCESS: "Brand inserted",
      CREATE_ERROR: "Error inserting brand",
      UPDATE_SUCCESS: "Brand updated",
      UPDATE_ERROR: "Error updating brand",
      DELETE_SUCCESS: "Brand deleted",
      DELETE_ERROR: "Error deleting brand",
      NOT_FOUND: "Brand not found",
      MISSING_ID: "Missing Brand id",
      INVALID_FORMAT: "Invalid Brand format",
    },
  },
};
